-- Typed models for the IgnavFlight SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class Airport
---@field city string
---@field code string
---@field country string
---@field name string

---@class AirportListMatch
---@field city? string
---@field code? string
---@field country? string
---@field name? string

---@class BookingLink
---@field adults? any
---@field children? any
---@field departure_date? any
---@field destination? any
---@field ignav_id? string
---@field inbound_carrier_code? any
---@field inbound_flight_number? number
---@field infants_in_seat? any
---@field infants_on_lap? any
---@field market? any
---@field origin? any
---@field outbound_carrier_code? any
---@field outbound_flight_number? number
---@field return_date? any

---@class BookingLinkCreateData
---@field adults? any
---@field children? any
---@field departure_date? any
---@field destination? any
---@field ignav_id? string
---@field inbound_carrier_code? any
---@field inbound_flight_number? number
---@field infants_in_seat? any
---@field infants_on_lap? any
---@field market? any
---@field origin? any
---@field outbound_carrier_code? any
---@field outbound_flight_number? number
---@field return_date? any

---@class FareSearchModel
---@field adults? number
---@field airlines_exclude? any
---@field airlines_include? any
---@field allow_self_transfer? boolean
---@field cabin_class? string
---@field children? number
---@field infants_in_seat? number
---@field infants_on_lap? number
---@field itineraries table
---@field legs table
---@field market? string
---@field max_price? any
---@field min_carry_on_bags? any
---@field min_checked_bags? any

---@class FareSearchModelCreateData
---@field adults? number
---@field airlines_exclude? any
---@field airlines_include? any
---@field allow_self_transfer? boolean
---@field cabin_class? string
---@field children? number
---@field infants_in_seat? number
---@field infants_on_lap? number
---@field itineraries table
---@field legs table
---@field market? string
---@field max_price? any
---@field min_carry_on_bags? any
---@field min_checked_bags? any

---@class FareSearchResponseModel
---@field adults? number
---@field airlines_exclude? any
---@field airlines_include? any
---@field allow_self_transfer? boolean
---@field cabin_class? string
---@field children? number
---@field departure_date string
---@field departure_time_range? any
---@field destination string
---@field infants_in_seat? number
---@field infants_on_lap? number
---@field itineraries table
---@field market? string
---@field max_price? any
---@field max_stops? any
---@field min_carry_on_bags? any
---@field min_checked_bags? any
---@field origin string
---@field return_date? any
---@field return_time_range? any

---@class FareSearchResponseModelCreateData
---@field adults? number
---@field airlines_exclude? any
---@field airlines_include? any
---@field allow_self_transfer? boolean
---@field cabin_class? string
---@field children? number
---@field departure_date string
---@field departure_time_range? any
---@field destination string
---@field infants_in_seat? number
---@field infants_on_lap? number
---@field itineraries table
---@field market? string
---@field max_price? any
---@field max_stops? any
---@field min_carry_on_bags? any
---@field min_checked_bags? any
---@field origin string
---@field return_date? any
---@field return_time_range? any

local M = {}

return M
