# IgnavFlight SDK configuration


def make_config():
    return {
        "main": {
            "name": "IgnavFlight",
        },
        "feature": {
            "test": {
        "options": {
          "active": False,
        },
      },
        },
        "options": {
            "base": "https://ignav.com",
            "auth": {
                "prefix": "",
            },
            "headers": {
        "content-type": "application/json",
      },
            "entity": {
                "airport": {},
                "booking_link": {},
                "fare_search_model": {},
                "fare_search_response_model": {},
            },
        },
        "entity": {
      "airport": {
        "fields": [
          {
            "active": True,
            "name": "city",
            "req": True,
            "type": "`$STRING`",
            "index$": 0,
          },
          {
            "active": True,
            "name": "code",
            "req": True,
            "type": "`$STRING`",
            "index$": 1,
          },
          {
            "active": True,
            "name": "country",
            "req": True,
            "type": "`$STRING`",
            "index$": 2,
          },
          {
            "active": True,
            "name": "name",
            "req": True,
            "type": "`$STRING`",
            "index$": 3,
          },
        ],
        "name": "airport",
        "op": {
          "list": {
            "input": "data",
            "name": "list",
            "points": [
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "example": 10,
                      "kind": "query",
                      "name": "limit",
                      "orig": "limit",
                      "reqd": False,
                      "type": "`$INTEGER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "q",
                      "orig": "q",
                      "reqd": True,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "method": "GET",
                "orig": "/api/airports",
                "parts": [
                  "api",
                  "airports",
                ],
                "select": {
                  "exist": [
                    "limit",
                    "q",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
            ],
            "key$": "list",
          },
        },
        "relations": {
          "ancestors": [],
        },
      },
      "booking_link": {
        "fields": [
          {
            "active": True,
            "name": "adult",
            "req": False,
            "type": "`$ANY`",
            "index$": 0,
          },
          {
            "active": True,
            "name": "child",
            "req": False,
            "type": "`$ANY`",
            "index$": 1,
          },
          {
            "active": True,
            "name": "departure_date",
            "req": False,
            "type": "`$ANY`",
            "index$": 2,
          },
          {
            "active": True,
            "name": "destination",
            "req": False,
            "type": "`$ANY`",
            "index$": 3,
          },
          {
            "active": True,
            "name": "ignav_id",
            "req": False,
            "type": "`$STRING`",
            "index$": 4,
          },
          {
            "active": True,
            "name": "inbound_carrier_code",
            "req": False,
            "type": "`$ANY`",
            "index$": 5,
          },
          {
            "active": True,
            "name": "inbound_flight_number",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 6,
          },
          {
            "active": True,
            "name": "infants_in_seat",
            "req": False,
            "type": "`$ANY`",
            "index$": 7,
          },
          {
            "active": True,
            "name": "infants_on_lap",
            "req": False,
            "type": "`$ANY`",
            "index$": 8,
          },
          {
            "active": True,
            "name": "market",
            "req": False,
            "type": "`$ANY`",
            "index$": 9,
          },
          {
            "active": True,
            "name": "origin",
            "req": False,
            "type": "`$ANY`",
            "index$": 10,
          },
          {
            "active": True,
            "name": "outbound_carrier_code",
            "req": False,
            "type": "`$ANY`",
            "index$": 11,
          },
          {
            "active": True,
            "name": "outbound_flight_number",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 12,
          },
          {
            "active": True,
            "name": "return_date",
            "req": False,
            "type": "`$ANY`",
            "index$": 13,
          },
        ],
        "name": "booking_link",
        "op": {
          "create": {
            "input": "data",
            "name": "create",
            "points": [
              {
                "active": True,
                "args": {},
                "method": "POST",
                "orig": "/api/fares/booking-links",
                "parts": [
                  "api",
                  "fares",
                  "booking-links",
                ],
                "select": {},
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
            ],
            "key$": "create",
          },
        },
        "relations": {
          "ancestors": [],
        },
      },
      "fare_search_model": {
        "fields": [
          {
            "active": True,
            "name": "adult",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 0,
          },
          {
            "active": True,
            "name": "airlines_exclude",
            "req": False,
            "type": "`$ANY`",
            "index$": 1,
          },
          {
            "active": True,
            "name": "airlines_include",
            "req": False,
            "type": "`$ANY`",
            "index$": 2,
          },
          {
            "active": True,
            "name": "allow_self_transfer",
            "req": False,
            "type": "`$BOOLEAN`",
            "index$": 3,
          },
          {
            "active": True,
            "name": "cabin_class",
            "req": False,
            "type": "`$STRING`",
            "index$": 4,
          },
          {
            "active": True,
            "name": "child",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 5,
          },
          {
            "active": True,
            "name": "infants_in_seat",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 6,
          },
          {
            "active": True,
            "name": "infants_on_lap",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 7,
          },
          {
            "active": True,
            "name": "itinerary",
            "req": True,
            "type": "`$ARRAY`",
            "index$": 8,
          },
          {
            "active": True,
            "name": "leg",
            "req": True,
            "type": "`$ARRAY`",
            "index$": 9,
          },
          {
            "active": True,
            "name": "market",
            "req": False,
            "type": "`$STRING`",
            "index$": 10,
          },
          {
            "active": True,
            "name": "max_price",
            "req": False,
            "type": "`$ANY`",
            "index$": 11,
          },
          {
            "active": True,
            "name": "min_carry_on_bag",
            "req": False,
            "type": "`$ANY`",
            "index$": 12,
          },
          {
            "active": True,
            "name": "min_checked_bag",
            "req": False,
            "type": "`$ANY`",
            "index$": 13,
          },
        ],
        "name": "fare_search_model",
        "op": {
          "create": {
            "input": "data",
            "name": "create",
            "points": [
              {
                "active": True,
                "args": {},
                "method": "POST",
                "orig": "/api/fares/search",
                "parts": [
                  "api",
                  "fares",
                  "search",
                ],
                "select": {},
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
            ],
            "key$": "create",
          },
        },
        "relations": {
          "ancestors": [],
        },
      },
      "fare_search_response_model": {
        "fields": [
          {
            "active": True,
            "name": "adult",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 0,
          },
          {
            "active": True,
            "name": "airlines_exclude",
            "req": False,
            "type": "`$ANY`",
            "index$": 1,
          },
          {
            "active": True,
            "name": "airlines_include",
            "req": False,
            "type": "`$ANY`",
            "index$": 2,
          },
          {
            "active": True,
            "name": "allow_self_transfer",
            "req": False,
            "type": "`$BOOLEAN`",
            "index$": 3,
          },
          {
            "active": True,
            "name": "cabin_class",
            "req": False,
            "type": "`$STRING`",
            "index$": 4,
          },
          {
            "active": True,
            "name": "child",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 5,
          },
          {
            "active": True,
            "name": "departure_date",
            "req": True,
            "type": "`$STRING`",
            "index$": 6,
          },
          {
            "active": True,
            "name": "departure_time_range",
            "req": False,
            "type": "`$ANY`",
            "index$": 7,
          },
          {
            "active": True,
            "name": "destination",
            "req": True,
            "type": "`$STRING`",
            "index$": 8,
          },
          {
            "active": True,
            "name": "infants_in_seat",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 9,
          },
          {
            "active": True,
            "name": "infants_on_lap",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 10,
          },
          {
            "active": True,
            "name": "itinerary",
            "req": True,
            "type": "`$ARRAY`",
            "index$": 11,
          },
          {
            "active": True,
            "name": "market",
            "req": False,
            "type": "`$STRING`",
            "index$": 12,
          },
          {
            "active": True,
            "name": "max_price",
            "req": False,
            "type": "`$ANY`",
            "index$": 13,
          },
          {
            "active": True,
            "name": "max_stop",
            "req": False,
            "type": "`$ANY`",
            "index$": 14,
          },
          {
            "active": True,
            "name": "min_carry_on_bag",
            "req": False,
            "type": "`$ANY`",
            "index$": 15,
          },
          {
            "active": True,
            "name": "min_checked_bag",
            "req": False,
            "type": "`$ANY`",
            "index$": 16,
          },
          {
            "active": True,
            "name": "origin",
            "req": True,
            "type": "`$STRING`",
            "index$": 17,
          },
          {
            "active": True,
            "name": "return_date",
            "op": {
              "create": {
                "req": True,
                "type": "`$STRING`",
              },
            },
            "req": False,
            "type": "`$ANY`",
            "index$": 18,
          },
          {
            "active": True,
            "name": "return_time_range",
            "req": False,
            "type": "`$ANY`",
            "index$": 19,
          },
        ],
        "name": "fare_search_response_model",
        "op": {
          "create": {
            "input": "data",
            "name": "create",
            "points": [
              {
                "active": True,
                "args": {},
                "method": "POST",
                "orig": "/api/fares/one-way",
                "parts": [
                  "api",
                  "fares",
                  "one-way",
                ],
                "select": {},
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
              {
                "active": True,
                "args": {},
                "method": "POST",
                "orig": "/api/fares/round-trip",
                "parts": [
                  "api",
                  "fares",
                  "round-trip",
                ],
                "select": {},
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 1,
              },
            ],
            "key$": "create",
          },
        },
        "relations": {
          "ancestors": [],
        },
      },
    },
    }
